spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_api_2
    username: root
    password: Nah1211zz@
  jpa:
    hibernate:
      ddl-auto: update  # T? ??ng c?p nh?t c?u tr?c database
    show-sql: true  # Hi?n th? c?c c?u l?nh SQL trong console
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    pool-name: HikariCP
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 6000
jwt:
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    persistAuthorization: true
  default-produces-media-type: application/json


